language: node_js
node_js:
  - "lts/*"
script:
  - npm run start-test &
  - bg_pid=$!
  - sleep 30
  - npm test
  - sleep 10
  - kill $bg_pid
  - sleep 10
  - ls 
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js