language: node_js
node_js:
  - "lts/*"
script:
  - npm run start-test &
  - bg_pid=$!
  - sleep 30
  - npm test
  - sleep 10
  - kill $bg_pid
after_script:
  - sleep 10
  - ls 
  - ls ./coverage
  - cat ./coverage/lcov.info 