language: node_js
node_js:
  - "lts/*"
script:
  - node index.js &
  - npm test

after_success:
  - ./node_modules/bin/coveralls.js
  - ./node_modules/.bin/mocha test/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js